### ISSUE TITLE
[Doc enhancement] Adding specific dependencies in README

### ISSUE THREAD

**Issue by insukcho** [swiftype/swiftype-app-search-java#19]
So far, the client library is not available to be managed automatically.
The user should download the library and need to add 2 more dependencies to the client application.
Currently, the user should open `build.gradle` file and put is the user's gradle config or non-gradle configuration like maven.

I would suggest adding the configuration snippet for 2 libraries(gson, httpclient) with gradle config and maven one. That will help the user use the client library w/o failing to run the API.

Gradle configuration sample will be like below.
```
dependencies {
  compile 'com.google.code.gson:gson:2.8.2'
  compile 'org.apache.httpcomponents:httpclient:4.5.5'
}
```

Maven configuration sample will be like below.
```
	<dependencies>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.2</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.5</version>
		</dependency>
	</dependencies>
```

Want to share [one reference doc](https://spring.io/guides/gs/serving-web-content/) from `spring.io`. It is very easy to install without any additional effort to find dependencies.

**Comment by JasonStoltz** [comment]
Thanks for this!
